QT += widgets network multimedia concurrent websockets

CONFIG += c++11

TARGET = vocekit
TEMPLATE = app

SOURCES += \
    src/api/api_client_utils.cpp \
    src/app/application_events.cpp \
    src/app/selection_context_feature.cpp \
    src/app/vocekit_application_runtime.cpp \
    src/capture/screen_capture_overlay.cpp \
    src/capture/screenshot_launcher.cpp \
    src/capture/screenshot_result_window.cpp \
    src/capture/screenshot_types.cpp \
    src/config/app_settings_json.cpp \
    src/config/app_settings_defaults.cpp \
    src/config/selection_context_action_customization.cpp \
    src/config/app_settings_store.cpp \
    src/config/app_paths.cpp \
    src/config/baidu_sample_parser.cpp \
    src/config/function_flow_json.cpp \
    src/config/prompt_save_route.cpp \
    src/config/secret_config.cpp \
    src/config/secret_store.cpp \
    src/controllers/function_command_adapters.cpp \
    src/controllers/function_command_controller.cpp \
    src/controllers/function_flow_execution_controller.cpp \
    src/controllers/function_flow_editor_controller.cpp \
    src/controllers/function_flow_plan_cache.cpp \
    src/controllers/function_flow_publication_service.cpp \
    src/controllers/function_flow_result_controller.cpp \
    src/controllers/function_flow_runtime_adapters.cpp \
    src/controllers/selected_text_workflow_adapters.cpp \
    src/controllers/selected_text_workflow_controller.cpp \
    src/controllers/screenshot_workflow_controller.cpp \
    src/controllers/selection_context_action_controller.cpp \
    src/controllers/selection_context_coordinator.cpp \
    src/controllers/selection_context_policy.cpp \
    src/controllers/tray_controller.cpp \
    src/controllers/vocabulary_quick_add_adapters.cpp \
    src/controllers/vocabulary_quick_add_controller.cpp \
    src/controllers/voice_controller.cpp \
    src/controllers/voice_run_lifecycle_adapters.cpp \
    src/controllers/voice_run_lifecycle_controller.cpp \
    src/controllers/voice_result_presentation_controller.cpp \
    src/controllers/voice_recording_workflow_controller.cpp \
    src/domain/function_catalog.cpp \
    src/domain/function_flow_compiler.cpp \
    src/domain/function_flow_errors.cpp \
    src/domain/function_flow_graph.cpp \
    src/domain/function_flow_model_message.cpp \
    src/domain/function_flow_ports.cpp \
    src/domain/function_flow_runtime_types.cpp \
    src/domain/function_flow_scheduler.cpp \
    src/domain/function_flow_validation.cpp \
    src/domain/function_settings.cpp \
    src/domain/selection_context_actions.cpp \
    src/domain/history_filter.cpp \
    src/domain/history_modes.cpp \
    src/domain/history_record_builder.cpp \
    src/domain/history_selection.cpp \
    src/domain/history_text.cpp \
    src/domain/history_types.cpp \
    src/domain/prompt_runtime_library.cpp \
    src/domain/vocabulary_ai.cpp \
    src/domain/vocabulary_candidates.cpp \
    src/domain/vocabulary_io.cpp \
    src/domain/vocabulary_runtime.cpp \
    src/domain/voice_function_execution_pipeline.cpp \
    src/domain/voice_history_recorder.cpp \
    src/domain/voice_history_request_builder.cpp \
    src/domain/voice_input_processing_pipeline.cpp \
    src/domain/voice_result_completion_executor.cpp \
    src/domain/voice_result_rerun_executor.cpp \
    src/domain/voice_result_stream_executor.cpp \
    src/domain/voice_run_formatter.cpp \
    src/domain/voice_run_context.cpp \
    src/domain/voice_run_session.cpp \
    src/domain/voice_screenshot_session.cpp \
    src/domain/voice_run_executor.cpp \
    src/domain/voice_run_planner.cpp \
    src/file_utils.cpp \
    src/input/global_hotkeys.cpp \
    src/faq_paging.cpp \
    src/input/hotkey_definitions.cpp \
    src/input/hotkey_parser.cpp \
    src/input/hotkey_refresh_coordinator.cpp \
    src/input/hotkey_settings_snapshot.cpp \
    src/input/hold_to_talk.cpp \
    src/input/selected_text_reader.cpp \
    src/input/selection_coordinate_mapper.cpp \
    src/input/selection_observer.cpp \
    src/input/selection_probe_runner.cpp \
    src/input/voice_input_collector.cpp \
    src/main.cpp \
    src/ocr/ocr_cloud_client.cpp \
    src/ocr/ocr_batch_queue.cpp \
    src/ocr/ocr_batch_text.cpp \
    src/ocr/ocr_helper_process.cpp \
    src/ocr/ocr_manager.cpp \
    src/ocr/screenshot_ocr_config.cpp \
    src/output/clipboard_writer.cpp \
    src/output/voice_result_popup_builder.cpp \
    src/output/result_output_router.cpp \
    src/output/voice_result_output_dispatcher.cpp \
    src/output/classic_auto_write_executor.cpp \
    src/tasks/selection_context_model_request.cpp \
    src/tasks/selection_context_model_runner.cpp \
    src/platform/windows_autostart.cpp \
    src/providers/built_in_provider_factory.cpp \
    src/providers/baidu_realtime_speech_protocol.cpp \
    src/providers/baidu_speech_provider.cpp \
    src/providers/baidu_streaming_speech_session.cpp \
    src/providers/claude_model_provider.cpp \
    src/providers/custom_speech_provider.cpp \
    src/providers/deepseek_model_provider.cpp \
    src/providers/model_catalog.cpp \
    src/providers/network_request_executor.cpp \
    src/providers/network_error_messages.cpp \
    src/providers/openai_compatible_model_provider.cpp \
    src/providers/provider_configuration.cpp \
    src/providers/provider_network_transport.cpp \
    src/providers/provider_streaming_websocket_transport.cpp \
    src/providers/provider_websocket_transport.cpp \
    src/providers/provider_registry.cpp \
    src/providers/streaming_speech_session_factory.cpp \
    src/providers/streaming_speech_session_factory_default.cpp \
    src/providers/streaming_transcript_accumulator.cpp \
    src/providers/xfyun_speech_provider.cpp \
    src/providers/xfyun_speech_protocol.cpp \
    src/providers/xfyun_streaming_speech_session.cpp \
    src/providers/windows_speech_helper_client.cpp \
    src/providers/windows_speech_helper_protocol.cpp \
    src/providers/windows_speech_provider.cpp \
    src/providers/windows_streaming_speech_session.cpp \
    src/recording/segmented_recording.cpp \
    src/recording/voice_audio_recorder_adapter.cpp \
    src/recording/voice_long_recording_session.cpp \
    src/recording/voice_recording_capture.cpp \
    src/recording/voice_recording_coordinator.cpp \
    src/recording/voice_recording_countdown.cpp \
    src/recording/voice_recording_lifecycle.cpp \
    src/result_flow_config.cpp \
    src/runtime_crash_handler.cpp \
    src/runtime_log.cpp \
    src/runtime/function_flow_runtime_log.cpp \
    src/storage/history_archive.cpp \
    src/storage/history_paths.cpp \
    src/storage/history_export.cpp \
    src/storage/history_favorites.cpp \
    src/storage/history_record_service.cpp \
    src/storage/history_store.cpp \
    src/storage/prompt_library_store.cpp \
    src/storage/vocabulary_store.cpp \
    src/tasks/cancellation_token.cpp \
    src/tasks/diagnostic_task_runner.cpp \
    src/tasks/diagnostic_helpers.cpp \
    src/tasks/function_flow_model_task_runner.cpp \
    src/tasks/history_segment_retry_task.cpp \
    src/tasks/interface_self_check_task.cpp \
    src/tasks/microphone_diagnostic_task.cpp \
    src/tasks/model_request_task.cpp \
    src/tasks/model_provider_request_task.cpp \
    src/tasks/network_diagnostics_task.cpp \
    src/tasks/processing_guard.cpp \
    src/tasks/selected_text_diagnostic_task.cpp \
    src/tasks/screenshot_text_action_task.cpp \
    src/tasks/screenshot_text_action_plan.cpp \
    src/tasks/speech_recognition_task.cpp \
    src/tasks/voice_long_recording_completion_executor.cpp \
    src/tasks/voice_long_recording_recognition_coordinator.cpp \
    src/tasks/voice_long_recording_result_builder.cpp \
    src/tasks/voice_long_recording_segment_executor.cpp \
    src/tasks/voice_recording_completion_executor.cpp \
    src/tasks/voice_speech_recognition_executor.cpp \
    src/tasks/voice_model_processing_task.cpp \
    src/tasks/voice_model_runtime_settings.cpp \
    src/tasks/vocabulary_diagnostic_task.cpp \
    src/tasks/vocabulary_suggestion_plan.cpp \
    src/tasks/vocabulary_suggestion_task.cpp \
    src/ui/attention_message.cpp \
    src/ui/app_dialogs.cpp \
    src/ui/basic_settings_section.cpp \
    src/ui/chinese_text_context_menu.cpp \
    src/ui/command_center_shell.cpp \
    src/ui/command_center_shell_access_factory.cpp \
    src/ui/custom_function_creation_coordinator.cpp \
    src/ui/command_search_router.cpp \
    src/ui/current_status_panel.cpp \
    src/ui/current_status_snapshot.cpp \
    src/ui/diagnostic_action_card.cpp \
    src/ui/diagnostics_page_factory.cpp \
    src/ui/diagnostics_panel.cpp \
    src/ui/diagnostics_settings_snapshot.cpp \
    src/ui/faq_panel.cpp \
    src/ui/floating_bar_test_card.cpp \
    src/ui/function_canvas_visual_style.cpp \
    src/ui/function_canvas_view.cpp \
    src/ui/function_canvas_edge_item.cpp \
    src/ui/function_canvas_editor.cpp \
    src/ui/function_canvas_inspector.cpp \
    src/ui/function_canvas_node_item.cpp \
    src/ui/function_canvas_palette.cpp \
    src/ui/function_canvas_scene.cpp \
    src/ui/function_command_page.cpp \
    src/ui/function_command_page_access_factory.cpp \
    src/ui/function_editor_coordinator.cpp \
    src/ui/function_management_page.cpp \
    src/ui/function_management_page_access_factory.cpp \
    src/ui/function_pages_access_factory.cpp \
    src/ui/function_pages_controller.cpp \
    src/ui/function_summary_formatter.cpp \
    src/ui/function_workspace_controller.cpp \
    src/ui/function_mode_grid.cpp \
    src/ui/function_mode_grid_access_factory.cpp \
    src/ui/history_entry_actions_controller.cpp \
    src/ui/history_directory_menu.cpp \
    src/ui/history_detail_dialog.cpp \
    src/ui/history_detail_widgets.cpp \
    src/ui/history_list_row.cpp \
    src/ui/history_list_view.cpp \
    src/ui/history_page.cpp \
    src/ui/history_page_access_factory.cpp \
    src/ui/history_page_controller.cpp \
    src/ui/api_settings_section.cpp \
    src/ui/windows_speech_settings_card.cpp \
    src/ui/custom_model_dialog_support.cpp \
    src/ui/history_settings_section.cpp \
    src/ui/shortcut_settings_section.cpp \
    src/ui/history_transfer_controller.cpp \
    src/ui/history_segments_widget.cpp \
    src/ui/home_page.cpp \
    src/ui/home_page_access_factory.cpp \
    src/ui/hub_application_event_coordinator.cpp \
    src/ui/hub_content_refresh_coordinator.cpp \
    src/ui/hub_content_pages_controller.cpp \
    src/ui/hub_function_workspace_controller.cpp \
    src/ui/hub_home_page_controller.cpp \
    src/ui/hub_navigation_controller.cpp \
    src/ui/hub_page_host_controller.cpp \
    src/ui/hub_page_composition.cpp \
    src/ui/hub_page_composition_access_factory.cpp \
    src/ui/hub_page_router.cpp \
    src/ui/hub_refresh_coordinator_action_factory.cpp \
    src/ui/hub_refresh_coordinator_bundle.cpp \
    src/ui/hub_settings_refresh_coordinator.cpp \
    src/ui/hub_settings_state.cpp \
    src/ui/hub_utility_pages_controller.cpp \
    src/ui/hub_window.cpp \
    src/ui/interface_self_check_card.cpp \
    src/ui/log_pagination_snapshot.cpp \
    src/ui/logs_panel.cpp \
    src/ui/microphone_input_test_card.cpp \
    src/ui/mode_card_frame.cpp \
    src/ui/network_diagnostics_card.cpp \
    src/ui/ocr_page.cpp \
    src/ui/ocr_page_access_factory.cpp \
    src/ui/ocr_page_controller.cpp \
    src/ui/prompt_access_factory.cpp \
    src/ui/prompts_panel.cpp \
    src/ui/prompt_settings_adapter.cpp \
    src/ui/recent_history_panel.cpp \
    src/ui/reorderable_card_column.cpp \
    src/ui/result_choice_popup.cpp \
    src/ui/result_popup_test_card.cpp \
    src/ui/selection_input_test_card.cpp \
    src/ui/selection_context_placement.cpp \
    src/ui/selection_context_action_editor.cpp \
    src/ui/selection_context_settings_card.cpp \
    src/ui/selection_context_toolbar.cpp \
    src/ui/selection_result_card.cpp \
    src/ui/settings_panel_access_factory.cpp \
    src/ui/settings_panel.cpp \
    src/ui/shortcut_display.cpp \
    src/ui/tab_bar_wheel_filter.cpp \
    src/ui/toggle_switch.cpp \
    src/ui/ui_style.cpp \
    src/ui/floating_bar_style_selector.cpp \
    src/ui/floating_bar.cpp \
    src/ui/floating_bar_surface.cpp \
    src/ui/vocabulary_candidates_dialog.cpp \
    src/ui/vocabulary_entry_dialog.cpp \
    src/ui/vocabulary_page.cpp \
    src/ui/vocabulary_page_access_factory.cpp \
    src/ui/vocabulary_page_controller.cpp \
    src/ui/vocabulary_quick_add_dialog.cpp \
    src/ui/vocabulary_test_card.cpp \
    src/ui/vocabulary_transfer_controller.cpp \
    src/ui/write_input_test_card.cpp \
    src/voiceassistant.cpp

HEADERS += \
    src/api/api_client_utils.h \
    src/app/application_events.h \
    src/app/vocekit_application_runtime.h \
    src/capture/screen_capture_overlay.h \
    src/capture/screenshot_launcher.h \
    src/capture/screenshot_result_window.h \
    src/capture/screenshot_types.h \
    src/config/app_settings_data.h \
    src/config/app_settings_defaults.h \
    src/config/app_settings_json.h \
    src/config/app_settings_store.h \
    src/config/selection_context_action_customization.h \
    src/config/app_paths.h \
    src/config/baidu_sample_parser.h \
    src/config/function_flow_json.h \
    src/config/prompt_save_route.h \
    src/config/secret_config.h \
    src/config/secret_store.h \
    src/controllers/function_command_controller.h \
    src/controllers/function_flow_execution_controller.h \
    src/controllers/function_flow_editor_controller.h \
    src/controllers/function_flow_plan_cache.h \
    src/controllers/function_flow_publication_service.h \
    src/controllers/function_flow_result_controller.h \
    src/controllers/function_flow_runtime_adapters.h \
    src/controllers/selected_text_workflow_controller.h \
    src/controllers/screenshot_workflow_controller.h \
    src/controllers/selection_context_action_controller.h \
    src/controllers/selection_context_coordinator.h \
    src/controllers/selection_context_policy.h \
    src/controllers/tray_controller.h \
    src/controllers/vocabulary_quick_add_controller.h \
    src/controllers/voice_controller.h \
    src/controllers/voice_controller_host.h \
    src/controllers/voice_run_lifecycle_controller.h \
    src/controllers/voice_result_presentation_controller.h \
    src/controllers/voice_recording_workflow_controller.h \
    src/domain/app_legacy_types.h \
    src/domain/execution_types.h \
    src/domain/function_catalog.h \
    src/domain/function_flow_compiler.h \
    src/domain/function_flow_errors.h \
    src/domain/function_flow_graph.h \
    src/domain/function_flow_model_message.h \
    src/domain/function_flow_ports.h \
    src/domain/function_flow_publication_types.h \
    src/domain/function_flow_runtime_types.h \
    src/domain/function_flow_scheduler.h \
    src/domain/function_flow_validation.h \
    src/domain/model_sampling_settings.h \
    src/domain/function_settings.h \
    src/domain/selection_context_actions.h \
    src/domain/history_filter.h \
    src/domain/history_modes.h \
    src/domain/history_record_builder.h \
    src/domain/history_selection.h \
    src/domain/history_text.h \
    src/domain/history_types.h \
    src/domain/operation_error.h \
    src/domain/prompt_runtime_library.h \
    src/domain/vocabulary_ai.h \
    src/domain/vocabulary_candidates.h \
    src/domain/vocabulary_io.h \
    src/domain/vocabulary_runtime.h \
    src/domain/voice_function_execution_pipeline.h \
    src/domain/voice_history_recorder.h \
    src/domain/voice_history_request_builder.h \
    src/domain/voice_input_processing_pipeline.h \
    src/domain/voice_result_completion_executor.h \
    src/domain/voice_result_rerun_executor.h \
    src/domain/voice_result_stream_executor.h \
    src/domain/voice_run_formatter.h \
    src/domain/voice_run_context.h \
    src/domain/voice_run_session.h \
    src/domain/voice_screenshot_session.h \
    src/domain/voice_run_executor.h \
    src/domain/voice_run_planner.h \
    src/file_utils.h \
    src/faq_paging.h \
    src/input/selection_coordinate_mapper.h \
    src/input/selection_observer.h \
    src/input/selection_probe_runner.h \
    src/input/selection_snapshot.h \
    src/tasks/selection_context_model_request.h \
    src/tasks/selection_context_model_runner.h \
    src/input/global_hotkeys.h \
    src/input/hotkey_definitions.h \
    src/input/hotkey_parser.h \
    src/input/hotkey_refresh_coordinator.h \
    src/input/hotkey_settings_snapshot.h \
    src/input/hold_to_talk.h \
    src/input/selected_text_reader.h \
    src/input/voice_input_collector.h \
    src/ocr/ocr_cloud_client.h \
    src/ocr/ocr_batch_queue.h \
    src/ocr/ocr_batch_text.h \
    src/ocr/ocr_helper_process.h \
    src/ocr/ocr_manager.h \
    src/ocr/ocr_types.h \
    src/ocr/screenshot_ocr_config.h \
    src/output/clipboard_writer.h \
    src/output/voice_result_popup_builder.h \
    src/output/result_output_router.h \
    src/output/voice_result_output_dispatcher.h \
    src/output/classic_auto_write_executor.h \
    src/platform/windows_autostart.h \
    src/recording/audio_recorder_legacy.h \
    src/providers/built_in_provider_factory.h \
    src/providers/baidu_realtime_speech_protocol.h \
    src/providers/baidu_speech_provider.h \
    src/providers/baidu_streaming_speech_session.h \
    src/providers/claude_model_provider.h \
    src/providers/custom_speech_provider.h \
    src/providers/deepseek_model_provider.h \
    src/providers/model_catalog.h \
    src/providers/network_request_executor.h \
    src/providers/network_error_messages.h \
    src/providers/model_provider.h \
    src/providers/openai_compatible_model_provider.h \
    src/providers/provider_configuration.h \
    src/providers/provider_network_transport.h \
    src/providers/provider_streaming_websocket_transport.h \
    src/providers/provider_websocket_transport.h \
    src/providers/provider_registry.h \
    src/providers/provider_types.h \
    src/providers/speech_provider.h \
    src/providers/streaming_speech_session.h \
    src/providers/streaming_speech_session_factory.h \
    src/providers/streaming_transcript_accumulator.h \
    src/providers/xfyun_speech_protocol.h \
    src/providers/xfyun_speech_provider.h \
    src/providers/xfyun_streaming_speech_session.h \
    src/providers/windows_speech_helper_client.h \
    src/providers/windows_speech_helper_protocol.h \
    src/providers/windows_speech_provider.h \
    src/providers/windows_streaming_speech_session.h \
    src/recording/segmented_recording.h \
    src/recording/voice_audio_recorder_adapter.h \
    src/recording/voice_long_recording_session.h \
    src/recording/voice_recording_capture.h \
    src/recording/voice_recording_coordinator.h \
    src/recording/voice_recording_countdown.h \
    src/recording/voice_recording_lifecycle.h \
    src/result_flow_config.h \
    src/runtime_crash_handler.h \
    src/runtime_log.h \
    src/runtime/function_flow_runtime_log.h \
    src/storage/history_archive.h \
    src/storage/history_paths.h \
    src/storage/history_export.h \
    src/storage/history_favorites.h \
    src/storage/history_record_service.h \
    src/storage/history_store.h \
    src/storage/prompt_library_store.h \
    src/storage/vocabulary_store.h \
    src/tasks/cancellation_token.h \
    src/tasks/diagnostic_task_runner.h \
    src/tasks/diagnostic_helpers.h \
    src/tasks/function_flow_model_task_runner.h \
    src/tasks/history_segment_retry_task.h \
    src/tasks/interface_self_check_task.h \
    src/tasks/microphone_diagnostic_task.h \
    src/tasks/model_request_task.h \
    src/tasks/network_diagnostics_task.h \
    src/tasks/processing_guard.h \
    src/tasks/selected_text_diagnostic_task.h \
    src/tasks/screenshot_text_action_task.h \
    src/tasks/screenshot_text_action_plan.h \
    src/tasks/speech_recognition_task.h \
    src/tasks/voice_long_recording_completion_executor.h \
    src/tasks/voice_long_recording_recognition_coordinator.h \
    src/tasks/voice_long_recording_result_builder.h \
    src/tasks/voice_long_recording_segment_executor.h \
    src/tasks/voice_recording_completion_executor.h \
    src/tasks/voice_speech_recognition_executor.h \
    src/tasks/voice_model_processing_task.h \
    src/tasks/voice_model_runtime_settings.h \
    src/tasks/vocabulary_diagnostic_task.h \
    src/tasks/vocabulary_suggestion_plan.h \
    src/tasks/vocabulary_suggestion_task.h \
    src/ui/attention_message.h \
    src/ui/app_dialogs.h \
    src/ui/basic_settings_section.h \
    src/ui/chinese_text_context_menu.h \
    src/ui/command_center_shell.h \
    src/ui/command_center_shell_access_factory.h \
    src/ui/custom_function_creation_coordinator.h \
    src/ui/command_search_router.h \
    src/ui/current_status_panel.h \
    src/ui/current_status_snapshot.h \
    src/app/selection_context_feature.h \
    src/ui/diagnostic_action_card.h \
    src/ui/diagnostics_page_factory.h \
    src/ui/diagnostics_panel.h \
    src/ui/diagnostics_settings_snapshot.h \
    src/ui/faq_panel.h \
    src/ui/floating_bar_test_card.h \
    src/ui/function_canvas_visual_style.h \
    src/ui/function_canvas_view.h \
    src/ui/function_canvas_edge_item.h \
    src/ui/function_canvas_editor.h \
    src/ui/function_canvas_inspector.h \
    src/ui/function_canvas_node_item.h \
    src/ui/function_canvas_palette.h \
    src/ui/function_canvas_scene.h \
    src/ui/function_flow_settings_access.h \
    src/ui/function_command_page.h \
    src/ui/function_command_page_access_factory.h \
    src/ui/function_editor_coordinator.h \
    src/ui/function_management_page.h \
    src/ui/function_management_page_access_factory.h \
    src/ui/function_pages_access_factory.h \
    src/ui/function_pages_controller.h \
    src/ui/function_summary_formatter.h \
    src/ui/function_workspace_controller.h \
    src/ui/function_mode_grid.h \
    src/ui/function_mode_grid_access_factory.h \
    src/ui/shortcut_display.h \
    src/ui/floating_bar.h \
    src/ui/history_row_frame.h \
    src/ui/history_entry_actions_controller.h \
    src/ui/history_directory_menu.h \
    src/ui/history_detail_dialog.h \
    src/ui/history_detail_widgets.h \
    src/ui/history_list_row.h \
    src/ui/history_list_view.h \
    src/ui/history_page.h \
    src/ui/history_page_access_factory.h \
    src/ui/history_page_controller.h \
    src/ui/api_settings_section.h \
    src/ui/windows_speech_settings_card.h \
    src/ui/custom_model_dialog_support.h \
    src/ui/history_settings_section.h \
    src/ui/shortcut_settings_section.h \
    src/ui/history_transfer_controller.h \
    src/ui/history_segments_widget.h \
    src/ui/home_page.h \
    src/ui/home_page_access_factory.h \
    src/ui/hub_application_event_coordinator.h \
    src/ui/hub_content_refresh_coordinator.h \
    src/ui/hub_content_pages_controller.h \
    src/ui/hub_function_workspace_controller.h \
    src/ui/hub_home_page_controller.h \
    src/ui/hub_navigation_controller.h \
    src/ui/hub_page_host_controller.h \
    src/ui/hub_page_composition.h \
    src/ui/hub_page_composition_access_factory.h \
    src/ui/hub_page_router.h \
    src/ui/hub_refresh_coordinator_action_factory.h \
    src/ui/hub_refresh_coordinator_bundle.h \
    src/ui/hub_settings_refresh_coordinator.h \
    src/ui/hub_settings_state.h \
    src/ui/hub_utility_pages_controller.h \
    src/ui/hub_window.h \
    src/ui/interface_self_check_card.h \
    src/ui/log_pagination_snapshot.h \
    src/ui/logs_panel.h \
    src/ui/microphone_input_test_card.h \
    src/ui/mode_card_frame.h \
    src/ui/network_diagnostics_card.h \
    src/ui/ocr_page.h \
    src/ui/ocr_page_access_factory.h \
    src/ui/ocr_page_controller.h \
    src/ui/prompt_access_factory.h \
    src/ui/prompts_panel.h \
    src/ui/prompt_settings_adapter.h \
    src/ui/result_choice_popup.h \
    src/ui/recent_history_panel.h \
    src/ui/reorderable_card_column.h \
    src/ui/result_popup_test_card.h \
    src/ui/selection_input_test_card.h \
    src/ui/selection_context_placement.h \
    src/ui/selection_context_action_editor.h \
    src/ui/selection_context_settings_card.h \
    src/ui/selection_context_toolbar.h \
    src/ui/selection_result_card.h \
    src/ui/screen_position.h \
    src/ui/settings_panel_access_factory.h \
    src/ui/settings_panel.h \
    src/ui/tab_bar_wheel_filter.h \
    src/ui/toggle_switch.h \
    src/ui/ui_style.h \
    src/ui/floating_bar_style_selector.h \
    src/ui/floating_bar_surface.h \
    src/ui/vocabulary_candidates_dialog.h \
    src/ui/vocabulary_entry_dialog.h \
    src/ui/vocabulary_page.h \
    src/ui/vocabulary_page_access_factory.h \
    src/ui/vocabulary_page_controller.h \
    src/ui/vocabulary_quick_add_dialog.h \
    src/ui/vocabulary_test_card.h \
    src/ui/vocabulary_transfer_controller.h \
    src/ui/write_input_test_card.h \
    src/voiceassistant.h

win32:LIBS += -luser32 -lwtsapi32 -lole32 -loleaut32 -luuid
